name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to witco-oss
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_WITCO_OSS_HOMEBREW_WITCO }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          git remote add mirror git@github.com:witco-oss/homebrew-witco.git
          git push mirror main --force --tags
        env:
          GIT_SSH_COMMAND: ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no
