name: Mirror

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Tavern
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://tavern.witco.net/witco/homebrew-witco.git
          GIT_USERNAME: cincpro-github-actions
          GIT_PASSWORD: ${{ secrets.TAVERN_ACCESS_TOKEN }}
          PUSH_ALL_REFS: "false"

      - name: Mirror to witco-oss
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: git@github.com:witco-oss/homebrew-witco.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_WITCO_OSS_HOMEBREW_WITCO }}
          GIT_SSH_KNOWN_HOSTS: ${{ vars.GIT_SSH_KNOWN_HOSTS }}
          PUSH_ALL_REFS: "false"
